version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9010:9010"
    restart: unless-stopped
    depends_on: 
      - mysql
    networks:
      - backend
 
  mysql:
    restart: always
    image: mysql:5.7
    command:
      [
        "--sql_mode=",
        "--innodb_strict_mode=OFF",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password"
      ]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: defaultpass
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  backend:

volumes:
  db-data: